export const tableWidth = {
  index: 1182,
  left: 708,
  right: 4256,

  checkbox: 36,
  merchantUid: 128,
  merchantItemUid: 128,
  productName: 160,
  userName: 80,
  orderStatus: 80,
  claimStatus: 96,

  paidAt: 128,
  requestExchangeAt: 128,
  mainReason: 180,
  detaildReason: 200,
  AttachedImage: 160,
  exchangeCompletedAt: 128,
  shipmentCompany: 136,
  shipmentNumber: 216,
  pickupShipmentCompany: 136,
  pickupShipmentNumber: 216,
  pickupAgainShipmentCompany: 136,
  pickupAgainShipmentNumber: 216,

  option: 136,
  quantity: 80,
  originalPrice: 80,
  optionPrice: 80,
  discountPrice: 136,
  totalPrice: 136,
  shipmentPrice: 64,
  shipmentDistantPrice: 136,
  totalPaymentAmount: 136,

  userEmail: 144,
  userPhoneNumber: 112,
  recipientName: 64,
  recipientPhoneNumber: 112,

  pickupAddress: 112,
  pickupPostCode: 64,

  pickupAgainAddress: 112,
  pickupAgainPostCode: 64,

  exchangeRefusalAt: 128,
  refusalMainReason: 180,
  refusalDetaildReason: 200,
};

export const fixTableType = [
  {
    id: 0,
    label: "checkBox",
    width: tableWidth.checkbox,
    value: "checkBox",
  },
  {
    id: 1,
    label: "주문번호",
    width: tableWidth.merchantUid,
    value: "merchantUid",
  },
  {
    id: 2,
    label: "상품 주문번호",
    width: tableWidth.merchantItemUid,
    value: "merchantItemUid",
  },
  {
    id: 3,
    label: "주문 상품",
    width: tableWidth.productName,
    value: "productName",
  },
  {
    id: 4,
    label: "구매자 명",
    width: tableWidth.userName,
    value: "userName",
  },
  {
    id: 5,
    label: "주문 상태",
    width: tableWidth.orderStatus,
    value: "orderStatus",
  },
  {
    id: 6,
    label: "클레임 상태",
    width: tableWidth.claimStatus,
    value: "claimStatus",
  },
];

export const scrollTableType = [
  {
    id: 0,
    label: "결제일",
    width: tableWidth.paidAt,
    value: "paidAt",
  },
  {
    id: 1,
    label: "교환요청일",
    width: tableWidth.requestExchangeAt,
    value: "requestExchangeAt",
  },
  {
    id: 2,
    label: "대표사유",
    width: tableWidth.mainReason,
    value: "mainReason",
  },
  {
    id: 3,
    label: "상세사유",
    width: tableWidth.detaildReason,
    value: "detaildReason",
  },
  {
    id: 4,
    label: "첨부사진",
    width: tableWidth.AttachedImage,
    value: "AttachedImage",
  },
  {
    id: 5,
    label: "교환 완료일",
    width: tableWidth.exchangeCompletedAt,
    value: "exchangeCompletedAt",
  },
  {
    id: 6,
    label: "원배송 택배사",
    width: tableWidth.shipmentCompany,
    value: "shipmentCompany",
  },
  {
    id: 7,
    label: "원배송 송장번호",
    width: tableWidth.shipmentNumber,
    value: "shipmentNumber",
  },
  {
    id: 8,
    label: "수거배송 택배사",
    width: tableWidth.pickupShipmentCompany,
    value: "pickupShipmentCompany",
  },
  {
    id: 9,
    label: "수거배송 송장번호",
    width: tableWidth.pickupShipmentNumber,
    value: "pickupShipmentNumber",
  },
  {
    id: 10,
    label: "재배송 택배사",
    width: tableWidth.pickupAgainShipmentCompany,
    value: "pickupAgainShipmentCompany",
  },
  {
    id: 11,
    label: "재배송 송장번호",
    width: tableWidth.pickupAgainShipmentNumber,
    value: "pickupAgainShipmentNumber",
  },
  {
    id: 12,
    label: "옵션",
    width: tableWidth.option,
    value: "option",
  },
  {
    id: 13,
    label: "상품개수",
    width: tableWidth.quantity,
    value: "quantity",
  },
  {
    id: 14,
    label: "상품가격",
    width: tableWidth.originalPrice,
    value: "originalPrice",
  },
  {
    id: 15,
    label: "옵션가격",
    width: tableWidth.optionPrice,
    value: "optionPrice",
  },
  {
    id: 16,
    label: "상품별 할인액",
    width: tableWidth.discountPrice,
    value: "discountPrice",
  },
  {
    id: 17,
    label: "상품별 총 금액",
    width: tableWidth.totalPrice,
    value: "totalPrice",
  },
  {
    id: 18,
    label: "배송비",
    width: tableWidth.shipmentPrice,
    value: "shipmentPrice",
  },
  {
    id: 19,
    label: "제주/도서 추가배송비",
    width: tableWidth.shipmentDistantPrice,
    value: "shipmentDistantPrice",
  },
  {
    id: 20,
    label: "총 결제 금액",
    width: tableWidth.totalPaymentAmount,
    value: "totalPaymentAmount",
  },
  {
    id: 21,
    label: "구매자 아이디",
    width: tableWidth.userEmail,
    value: "userEmail",
  },
  {
    id: 22,
    label: "구매자 전화번호",
    width: tableWidth.userPhoneNumber,
    value: "userPhoneNumber",
  },
  {
    id: 23,
    label: "수취인",
    width: tableWidth.recipientName,
    value: "recipientName",
  },
  {
    id: 24,
    label: "수취인 전화번호",
    width: tableWidth.recipientPhoneNumber,
    value: "recipientPhoneNumber",
  },
  {
    id: 25,
    label: "교환 수거지",
    width: tableWidth.pickupAddress,
    value: "pickupAddress",
  },
  {
    id: 26,
    label: "우편번호",
    width: tableWidth.pickupPostCode,
    value: "pickupPostCode",
  },
  {
    id: 27,
    label: "재배송지",
    width: tableWidth.pickupAgainAddress,
    value: "pickupAgainAddress",
  },
  {
    id: 28,
    label: "우편번호",
    width: tableWidth.pickupAgainPostCode,
    value: "pickupAgainPostCode",
  },
  {
    id: 29,
    label: "교환거절일",
    width: tableWidth.exchangeRefusalAt,
    value: "exchangeRefusalAt",
  },
  {
    id: 30,
    label: "거절대표사유",
    width: tableWidth.refusalMainReason,
    value: "refusalMainReason",
  },
  {
    id: 31,
    label: "거절상세사유",
    width: tableWidth.refusalDetaildReason,
    value: "refusalDetaildReason",
  },
];
