export const tableWidth = {
  index: 1182,
  left: 526,
  right: 3864,

  checkbox: 36,
  merchantitemUid: 128,
  productCode: 128,
  productName: 160,
  userName: 80,
  orderStatus: 80,
  claimStatus: 96,

  paidAt: 128,
  requestRefundAt: 128,
  mainReason: 180,
  detaildReason: 200,
  completedRefundAt: 128,
  AttachedImage: 160,
  shipmentCompany: 136,
  shipmentNumber: 216,
  refundShipmentCompany: 136,
  refundShipmentNumber: 216,
  option: 136,
  quantity: 80,
  originalPrice: 80,
  optionPrice: 80,
  discountPrice: 136,
  totalPrice: 136,
  shipmentPrice: 64,
  shipmentDistantPrice: 136,
  totalPaymentAmount: 136,
  totalRefundAmount: 136,
  userEmail: 144,
  userPhoneNumber: 112,
  recipientName: 64,
  recipientPhoneNumber: 112,
  refundAddress: 112,
  refundPostCode: 64,
  refusalRefundAt: 128,
  refusalMainReason: 180,
  refusalDetaildReason: 200,
};

export const fixTableType = [
  {
    id: 0,
    label: "checkBox",
    width: tableWidth.checkbox,
    value: "checkBox",
  },
  {
    id: 1,
    label: "주문번호",
    width: tableWidth.merchantitemUid,
    value: "merchantitemUid",
  },
  {
    id: 2,
    label: "상품 주문번호",
    width: tableWidth.productCode,
    value: "productCode",
  },
  {
    id: 3,
    label: "주문 상품",
    width: tableWidth.productName,
    value: "productName",
  },
  {
    id: 4,
    label: "구매자명",
    width: tableWidth.userName,
    value: "userName",
  },
  {
    id: 5,
    label: "주문 상태",
    width: tableWidth.orderStatus,
    value: "orderStatus",
  },
  {
    id: 6,
    label: "클래임 상태",
    width: tableWidth.claimStatus,
    value: "claimStatus",
  },
];

export const scrollTableType = [
  {
    id: 0,
    label: "결제일",
    width: tableWidth.paidAt,
    value: "paidAt",
  },
  {
    id: 1,
    label: "반품요청일",
    width: tableWidth.requestRefundAt,
    value: "requestRefundAt",
  },
  {
    id: 2,
    label: "대표사유",
    width: tableWidth.mainReason,
    value: "mainReason",
  },
  {
    id: 3,
    label: "상세사유",
    width: tableWidth.detaildReason,
    value: "detaildReason",
  },
  {
    id: 4,
    label: "첨부사진",
    width: tableWidth.AttachedImage,
    value: "AttachedImage",
  },
  {
    id: 5,
    label: "반품 완료일",
    width: tableWidth.completedRefundAt,
    value: "completedRefundAt",
  },
  {
    id: 6,
    label: "원배송 택배사",
    width: tableWidth.completedRefundAt,
    value: "completedRefundAt",
  },
  {
    id: 7,
    label: "원배송 송장번호",
    width: tableWidth.shipmentNumber,
    value: "shipmentNumber",
  },
  {
    id: 8,
    label: "수거배송 택배사",
    width: tableWidth.refundShipmentCompany,
    value: "refundShipmentCompany",
  },
  {
    id: 9,
    label: "수거배송 송장번호",
    width: tableWidth.refundShipmentNumber,
    value: "refundShipmentNumber",
  },
  {
    id: 10,
    label: "옵션",
    width: tableWidth.option,
    value: "option",
  },
  {
    id: 11,
    label: "상품개수",
    width: tableWidth.quantity,
    value: "quantity",
  },
  {
    id: 12,
    label: "상품가격",
    width: tableWidth.originalPrice,
    value: "originalPrice",
  },
  {
    id: 13,
    label: "옵션가격",
    width: tableWidth.optionPrice,
    value: "optionPrice",
  },
  {
    id: 14,
    label: "상품별 할인액",
    width: tableWidth.discountPrice,
    value: "discountPrice",
  },
  {
    id: 15,
    label: "상품별 총 금액",
    width: tableWidth.totalPrice,
    value: "totalPrice",
  },
  {
    id: 16,
    label: "배송비",
    width: tableWidth.shipmentPrice,
    value: "shipmentPrice",
  },
  {
    id: 17,
    label: "제주/도서 추가배송비",
    width: tableWidth.shipmentDistantPrice,
    value: "shipmentDistantPrice",
  },
  {
    id: 18,
    label: "총 결제 금액",
    width: tableWidth.totalPaymentAmount,
    value: "totalPaymentAmount",
  },
  {
    id: 19,
    label: "총 환불 금액",
    width: tableWidth.totalRefundAmount,
    value: "totalRefundAmount",
  },
  {
    id: 20,
    label: "구매자 아이디",
    width: tableWidth.userEmail,
    value: "userEmail",
  },
  {
    id: 21,
    label: "구매자 전화번호",
    width: tableWidth.userPhoneNumber,
    value: "userPhoneNumber",
  },
  {
    id: 22,
    label: "수취인",
    width: tableWidth.recipientName,
    value: "recipientName",
  },
  {
    id: 23,
    label: "수취인 전화번호",
    width: tableWidth.recipientPhoneNumber,
    value: "recipientPhoneNumber",
  },
  {
    id: 24,
    label: "반품 수거지",
    width: tableWidth.refundAddress,
    value: "refundAddress",
  },
  {
    id: 25,
    label: "우편번호",
    width: tableWidth.refundPostCode,
    value: "refundPostCode",
  },
  {
    id: 26,
    label: "반품거절일",
    width: tableWidth.refusalRefundAt,
    value: "refusalRefundAt",
  },
  {
    id: 27,
    label: "거절대표사유",
    width: tableWidth.refusalMainReason,
    value: "refusalMainReason",
  },
  {
    id: 27,
    label: "거절상세사유",
    width: tableWidth.refusalDetaildReason,
    value: "refusalDetaildReason",
  },
];
