export enum CategoryNames {
  HOMEDECO = "HOMEDECO",
  INCENSE = "INCENSE",
  CANDLE = "CANDLE",
  DIFFUSER_ROOMSPRAY = "DIFFUSER_ROOMSPRAY",
  OBJET = "OBJET",
  BASKET_TRAY = "BASKET_TRAY",
  POSTER_FRAME = "POSTER_FRAME",
  LIGHTING = "LIGHTING",
  MIRROR = "MIRROR",
  WATCH = "WATCH",
  MULTITAP_SOCKET = "MULTITAP_SOCKET",

  HOMEFABRIC = "HOMEFABRIC",
  BEDDING = "BEDDING",
  BLANKET = "BLANKET",
  FABRIC_POSTER = "FABRIC_POSTER",
  CUSHION = "CUSHION",
  RUG_MAT = "RUG_MAT",
  TISSUE_COVER = "TISSUE_COVER",
  HOMEWARE_SLIPPERS = "HOMEWARE_SLIPPERS",
  FABRIC_ETC = "FABRIC_ETC",

  HOMELIVING = "HOMELIVING",
  FURNITURE = "FURNITURE",
  BATHROOM = "BATHROOM",
  VASE_FLOWERPOT = "VASE_FLOWERPOT",
  PET = "PET",
  DIY = "DIY",

  TABLEWARE = "TABLEWARE",
  MUGCUP = "MUGCUP",
  GLASSCUP = "GLASSCUP",
  COFFEECUP_TEACUP = "COFFEECUP_TEACUP",
  PLATE = "PLATE",
  BOWL = "BOWL",
  CUTLERY = "CUTLERY",
  KITCHEN_SET = "KITCHEN_SET",
  KITCHEN_ETC = "KITCHEN_ETC",

  DIGITAL_ACC = "DIGITAL_ACC",
  PHONE_CASE = "PHONE_CASE",
  GRIPTOK = "GRIPTOK",
  EARPHONE_CASE = "EARPHONE_CASE",
  KEYRING = "KEYRING",
  STRAP = "STRAP",
  MOUSEPAD = "MOUSEPAD",

  WEARABLE = "WEARABLE",
  BAG = "BAG",
  POUCH = "POUCH",
  CAP_HAIR = "CAP_HAIR",
  ACCESSORIES = "ACCESSORIES",
  FASHION_ACCESSORIES = "FASHION_ACCESSORIES",

  STATIONERY = "STATIONERY",
  NOTE_MEMO = "NOTE_MEMO",
  STICKER_TAPE = "STICKER_TAPE",
  CARD_POSTCARD_LETTER = "CARD_POSTCARD_LETTER",
  WRITING_MATERIAL = "WRITING_MATERIAL",
  FILE_STAND = "FILE_STAND",
  STATIONERY_ACC = "STATIONERY_ACC",
  ALL_GIFT = "ALL_GIFT",
  COMING_OF_AGE_DAY = "COMING_OF_AGE_DAY",
  BE_GOOD_TO_PARENTS = "BE_GOOD_TO_PARENTS",
  HAPPY_BIRTHDAY = "HAPPY_BIRTHDAY",
  HOUSEWARMING = "HOUSEWARMING",
  CONTRATULATIONS_TO_NEW_BUSINESS = "CONTRATULATIONS_TO_NEW_BUSINESS",
}

export const CATEGORY_NAMES = {
  // HOMEDECO
  [CategoryNames.HOMEDECO]: "홈 데코",
  [CategoryNames.INCENSE]: "인센스",
  [CategoryNames.CANDLE]: "캔들",
  [CategoryNames.DIFFUSER_ROOMSPRAY]: "디퓨저/룸스프레이",
  [CategoryNames.OBJET]: "오브제",
  [CategoryNames.BASKET_TRAY]: "바스켓/트레이",
  [CategoryNames.POSTER_FRAME]: "포스터",
  [CategoryNames.LIGHTING]: "조명",
  [CategoryNames.MIRROR]: "거울",
  [CategoryNames.WATCH]: "시계",
  [CategoryNames.MULTITAP_SOCKET]: "멀티탭",
  // HOMEFABRIC
  [CategoryNames.HOMEFABRIC]: "홈 패브릭",
  [CategoryNames.BEDDING]: "침구류",
  [CategoryNames.BLANKET]: "담요",
  [CategoryNames.FABRIC_POSTER]: "패브릭포스터",
  [CategoryNames.CUSHION]: "쿠션",
  [CategoryNames.RUG_MAT]: "러그/매트",
  [CategoryNames.TISSUE_COVER]: "티슈커버",
  [CategoryNames.HOMEWARE_SLIPPERS]: "슬리퍼",
  [CategoryNames.FABRIC_ETC]: "패브릭 기타",
  // HOMELIVING
  [CategoryNames.HOMELIVING]: "홈리빙",
  [CategoryNames.FURNITURE]: "가구",
  [CategoryNames.BATHROOM]: "화장실 용품",
  [CategoryNames.VASE_FLOWERPOT]: "꽃병",
  [CategoryNames.PET]: "펫",
  [CategoryNames.DIY]: "조립식 (DIY)",
  // TABLEWARE
  [CategoryNames.TABLEWARE]: "테이블웨어",
  [CategoryNames.MUGCUP]: "머그컵",
  [CategoryNames.GLASSCUP]: "유리컵",
  [CategoryNames.COFFEECUP_TEACUP]: "커피잔/찻잔",
  [CategoryNames.PLATE]: "접시",
  [CategoryNames.BOWL]: "보울",
  [CategoryNames.CUTLERY]: "커틀러리",
  [CategoryNames.KITCHEN_SET]: "키친 세트",
  [CategoryNames.KITCHEN_ETC]: "키친 기타",
  // DIGITAL_ACC
  [CategoryNames.DIGITAL_ACC]: "디지털 악세서리",
  [CategoryNames.PHONE_CASE]: "폰케이스",
  [CategoryNames.GRIPTOK]: "그립톡",
  [CategoryNames.EARPHONE_CASE]: "이어폰케이스",
  [CategoryNames.KEYRING]: "키링",
  [CategoryNames.STRAP]: "스트랩",
  [CategoryNames.MOUSEPAD]: "마우스패드",
  // WEARABLE
  [CategoryNames.WEARABLE]: "웨어러블",
  [CategoryNames.BAG]: "가방",
  [CategoryNames.POUCH]: "파우치",
  [CategoryNames.CAP_HAIR]: "모자",
  [CategoryNames.ACCESSORIES]: "액세서리",
  [CategoryNames.FASHION_ACCESSORIES]: "패션 액세서리",
  // STATIONERY
  [CategoryNames.STATIONERY]: "문구류",
  [CategoryNames.NOTE_MEMO]: "메모장",
  [CategoryNames.STICKER_TAPE]: "스티커/테이프",
  [CategoryNames.CARD_POSTCARD_LETTER]: "카드/편지",
  [CategoryNames.WRITING_MATERIAL]: "필기류",
  [CategoryNames.FILE_STAND]: "파일 스탠드",
  [CategoryNames.STATIONERY_ACC]: "문구류 기타",
  // GIFT CATEGORIES
  [CategoryNames.ALL_GIFT]: "ALL",
  [CategoryNames.COMING_OF_AGE_DAY]: "성년 맞이",
  [CategoryNames.BE_GOOD_TO_PARENTS]: "부모님 효도",
  [CategoryNames.HAPPY_BIRTHDAY]: "생일 축하",
  [CategoryNames.HOUSEWARMING]: "집들이",
  [CategoryNames.CONTRATULATIONS_TO_NEW_BUSINESS]: "개업 축하",
};
