export enum CategoryNames {
  HOMEDECO = "HOMEDECO",
  INCENSE_HOLDER = "INCENSE_HOLDER",
  CANDLE_HOLDER = "CANDLE_HOLDER",
  HOME_FRAGRANCE = "HOME_FRAGRANCE",
  OBJET = "OBJET",
  BASKET_TRAY = "BASKET_TRAY",
  CASE_BOX = "CASE_BOX",
  POSTER_FRAME = "POSTER_FRAME",
  HANGING_MOBILE = "HANGING_MOBILE",
  LIGHTING = "LIGHTING",
  MIRROR = "MIRROR",
  WATCH = "WATCH",
  FURNITURE = "FURNITURE",
  VASE_FLOWERPOT = "VASE_FLOWERPOT",

  HOMEFABRIC = "HOMEFABRIC",
  BEDDING = "BEDDING",
  BLANKET = "BLANKET",
  FABRIC_POSTER = "FABRIC_POSTER",
  CUSHION = "CUSHION",
  RUG_MAT = "RUG_MAT",
  TISSUE_COVER = "TISSUE_COVER",
  TOWEL = "TOWEL",
  FABRIC_ETC = "FABRIC_ETC",

  TABLEWARE = "TABLEWARE",
  MUGCUP = "MUGCUP",
  GLASSCUP = "GLASSCUP",
  COFFEECUP_TEACUP = "COFFEECUP_TEACUP",
  BOWL = "BOWL",
  PLATE = "PLATE",
  TEA_COASTER = "TEA_COASTER",
  KITCHEN_SET = "KITCHEN_SET",
  KITCHEN_ETC = "KITCHEN_ETC",

  DIGITAL_ACC = "DIGITAL_ACC",
  PHONE_CASE = "PHONE_CASE",
  GRIPTOK = "GRIPTOK",
  EARPHONE_CASE = "EARPHONE_CASE",
  KEYRING = "KEYRING",
  MOUSEPAD = "MOUSEPAD",
  MULTITAP_SOCKET = "MULTITAP_SOCKET",
  DIGITAL_ACC_ETC = "DIGITAL_ACC_ETC",

  WEARABLE = "WEARABLE",
  BAG = "BAG",
  POUCH_WALLET = "POUCH_WALLET",
  CAP_HAIR = "CAP_HAIR",
  ACCESSORIES = "ACCESSORIES",
  FASHION_ACCESSORIES = "FASHION_ACCESSORIES",

  STATIONERY = "STATIONERY",
  CALENDER = "CALENDER",
  NOTE_MEMO = "NOTE_MEMO",
  STICKER_TAPE = "STICKER_TAPE",
  CARD_POSTCARD_LETTER = "CARD_POSTCARD_LETTER",
  FILE_STAND = "FILE_STAND",
  STATIONERY_ACC = "STATIONERY_ACC",

  COMING_OF_AGE_DAY = "COMING_OF_AGE_DAY",
  BE_GOOD_TO_PARENTS = "BE_GOOD_TO_PARENTS",
  HAPPY_BIRTHDAY = "HAPPY_BIRTHDAY",
  HOUSEWARMING = "HOUSEWARMING",
  CONTRATULATIONS_TO_NEW_BUSINESS = "CONTRATULATIONS_TO_NEW_BUSINESS",
}

export const CATEGORY_NAMES = {
  [CategoryNames.HOMEDECO]: "HOMEDECO",
  [CategoryNames.INCENSE_HOLDER]: "인센스&홀더",
  [CategoryNames.CANDLE_HOLDER]: "캔들&홀더",
  [CategoryNames.HOME_FRAGRANCE]: "홈프라그란스",
  [CategoryNames.OBJET]: "오브제",
  [CategoryNames.BASKET_TRAY]: "바스켓/트레이",
  [CategoryNames.CASE_BOX]: "케이스/함",
  [CategoryNames.POSTER_FRAME]: "포스터/액자",
  [CategoryNames.HANGING_MOBILE]: "행잉/모빌",
  [CategoryNames.LIGHTING]: "조명",
  [CategoryNames.MIRROR]: "거울",
  [CategoryNames.WATCH]: "시계",
  [CategoryNames.FURNITURE]: "가구",
  [CategoryNames.VASE_FLOWERPOT]: "화분/화병",

  [CategoryNames.HOMEFABRIC]: "HOMEFABRIC",
  [CategoryNames.BEDDING]: "침구",
  [CategoryNames.BLANKET]: "블랭킷",
  [CategoryNames.FABRIC_POSTER]: "패브릭 포스터",
  [CategoryNames.CUSHION]: "쿠션",
  [CategoryNames.RUG_MAT]: "러그/매트",
  [CategoryNames.TISSUE_COVER]: "티슈커버",
  [CategoryNames.TOWEL]: "수건",
  [CategoryNames.FABRIC_ETC]: "패브릭 기타",

  [CategoryNames.TABLEWARE]: "TABLEWARE",
  [CategoryNames.MUGCUP]: "머그컵",
  [CategoryNames.GLASSCUP]: "유리컵",
  [CategoryNames.COFFEECUP_TEACUP]: "잔&소서",
  [CategoryNames.BOWL]: "보울",
  [CategoryNames.PLATE]: "플레이트",
  [CategoryNames.TEA_COASTER]: "티코스터",
  [CategoryNames.KITCHEN_SET]: "키친세트",
  [CategoryNames.KITCHEN_ETC]: "키친잡화",

  [CategoryNames.DIGITAL_ACC]: "DIGITAL_ACC",
  [CategoryNames.PHONE_CASE]: "폰케이스",
  [CategoryNames.GRIPTOK]: "그립톡",
  [CategoryNames.EARPHONE_CASE]: "이어폰 케이스",
  [CategoryNames.KEYRING]: "키링",
  [CategoryNames.MOUSEPAD]: "마우스패드",
  [CategoryNames.MULTITAP_SOCKET]: "멀티탭/콘센트",
  [CategoryNames.DIGITAL_ACC_ETC]: "디지털 잡화",

  [CategoryNames.WEARABLE]: "WEARABLE",
  [CategoryNames.BAG]: "가방",
  [CategoryNames.POUCH_WALLET]: "파우치/지갑",
  [CategoryNames.CAP_HAIR]: "모자",
  [CategoryNames.ACCESSORIES]: "액세서리",
  [CategoryNames.FASHION_ACCESSORIES]: "패션 액세서리",

  [CategoryNames.STATIONERY]: "STATIONERY",
  [CategoryNames.CALENDER]: "캘린더",
  [CategoryNames.NOTE_MEMO]: "노트/메모",
  [CategoryNames.STICKER_TAPE]: "스티커/테이프",
  [CategoryNames.CARD_POSTCARD_LETTER]: "카드/엽서/편지지",
  [CategoryNames.FILE_STAND]: "파일/스탠드",
  [CategoryNames.STATIONERY_ACC]: "문구잡화",

  [CategoryNames.COMING_OF_AGE_DAY]: "성년 맞이",
  [CategoryNames.BE_GOOD_TO_PARENTS]: "부모님 효도",
  [CategoryNames.HAPPY_BIRTHDAY]: "생일 축하",
  [CategoryNames.HOUSEWARMING]: "집들이",
  [CategoryNames.CONTRATULATIONS_TO_NEW_BUSINESS]: "개업 축하",
};
