name: Chopsticks Client Seller Dev Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: ""
          REACT_APP_SERVER_URI: ${{secrets.REACT_APP_SERVER_URI}}
          REACT_APP_OAUTH_GOOGLE_CLIENT_ID: ${{secrets.REACT_APP_OAUTH_GOOGLE_CLIENT_ID}}
          REACT_APP_OAUTH_GOOGLE_CLIENT_PASSWORD: ${{secrets.REACT_APP_OAUTH_GOOGLE_CLIENT_PASSWORD}}
          REACT_APP_KAKAO_JAVASCRIPT_KEY: ${{secrets.REACT_APP_KAKAO_JAVASCRIPT_KEY}}
          REACT_APP_DATAHUB_API_URL_DEV: ${{secrets.REACT_APP_DATAHUB_API_URL_DEV}}
          REACT_APP_BUSINESS_AUTHENTICATION_API_KEY: ${{secrets.REACT_APP_BUSINESS_AUTHENTICATION_API_KEY}}
          REACT_APP_DATA_API_KEY: ${{secrets.REACT_APP_DATA_API_KEY}}
          REACT_APP_BIZM_PROFILE: ${{secrets.REACT_APP_BIZM_PROFILE}}
          REACT_APP_BIZM_PRODUCT_URL: ${{secrets.REACT_APP_BIZM_PRODUCT_URL}}
          REACT_APP_ECOLIFE_API_KEY: ${{secrets.REACT_APP_ECOLIFE_API_KEY}}

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --recursive \
          --region ap-northeast-2 \
          build s3://chopsticks-seller-frontend
