import { SearchQueryType } from "@models/sale";

export enum OrderSearchType {
  RECIPIENT_NAME = "RECIPIENT_NAME",
  RECIPIENT_PHONE_NUMBER = "RECIPIENT_PHONE_NUMBER",
  MERCHANT_UID = "MERCHANT_UID",
}

export const searchQueryType: Array<SearchQueryType> = [
  { id: 0, label: "구매자명", value: OrderSearchType.RECIPIENT_NAME },
  {
    id: 1,
    label: "구매자 전화번호",
    value: OrderSearchType.RECIPIENT_PHONE_NUMBER,
  },
  { id: 2, label: "주문번호", value: OrderSearchType.MERCHANT_UID },
];

export enum MenuStatusType {
  PRODUCT = "PRODUCT",
  SALE = "SALE",
  INQUIRY = "INQUIRY",
  SETTLEMENT = "SETTLEMENT",
  SHOP = "SHOP",
  NOTICE = "NOTICE",
}

export enum SaleMenuStatusType {
  ORDER = "ORDER",
  CANCEL = "CANCEL",
  EXCHANGE = "EXCHANGE",
  REFUND = "REFUND",
}

export enum OrderStatusGroup {
  ORDER = "ORDER",
  CANCEL = "CANCEL",
  REFUND = "REFUND",
  EXCHANGE = "EXCHANGE",
}

export enum OrderStatusType {
  ORDER = "ORDER",
  CLAIM = "CLAIM",
}

export enum OrderStatusName {
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  PREPARING = "PREPARING",
  SHIPPING = "SHIPPING",
  SHIPPING_COMPLETED = "SHIPPING_COMPLETED",
  CANCEL_REQUEST = "CANCEL_REQUEST",
  CANCEL_COMPLETED = "CANCEL_COMPLETED",
  CANCEL_ERROR = "CANCEL_ERROR",
  CANCEL_REFUSAL = "CANCEL_REFUSAL",
  REFUND_REQUEST = "REFUND_REQUEST",
  REFUND_PICK_UP_IN_PROGRESS = "REFUND_PICK_UP_IN_PROGRESS",
  REFUND_PICK_UP_COMPLETED = "REFUND_PICK_UP_COMPLETED",
  REFUND_COMPLETED = "REFUND_COMPLETED",
  REFUND_REFUSAL = "REFUND_REFUSAL",
  REFUND_ERROR = "REFUND_ERROR",
  EXCHANGE_REQUEST = "EXCHANGE_REQUEST",
  EXCHANGE_PICK_UP_IN_PROGRESS = "EXCHANGE_PICK_UP_IN_PROGRESS",
  EXCHANGE_PICK_UP_COMPLETED = "EXCHANGE_PICK_UP_COMPLETED",
  SHIPPING_AGAIN = "SHIPPING_AGAIN",
  EXCHANGE_COMPLETED = "EXCHANGE_COMPLETED",
  EXCHANGE_REFUSAL = "EXCHANGE_REFUSAL",
  EXCHANGE_ERROR = "EXCHANGE_ERROR",
  CONFIRM_PURCHASE = "CONFIRM_PURCHASE",
  PICK_UP_IN_PROGRESS = "PICK_UP_IN_PROGRESS",
  PICK_UP_COMPLETED = "PICK_UP_COMPLETED",
}

export const orderStatusNameType = {
  PAYMENT_COMPLETED: "새주문",
  PREPARING: "상품준비중",
  SHIPPING: "배송중",
  SHIPPING_COMPLETED: "배송 완료",
  CANCEL_REQUEST: "취소 요청",
  CANCEL_COMPLETED: "취소 완료",
  CANCEL_ERROR: "취소 실패",
  CANCEL_REFUSAL: "취소 거절",
  REFUND_REQUEST: "환불 요청",
  REFUND_PICK_UP_IN_PROGRESS: "환불 수거 진행중",
  REFUND_PICK_UP_COMPLETED: "환불 수거 완료",
  REFUND_COMPLETED: "환불 완료",
  REFUND_REFUSAL: "환불 거절",
  REFUND_ERROR: "환불 실패",
  EXCHANGE_REQUEST: "교환 요청",
  EXCHANGE_PICK_UP_IN_PROGRESS: "교환 수거중",
  EXCHANGE_PICK_UP_COMPLETED: "교환 수거 완료",
  SHIPPING_AGAIN: "재배송",
  EXCHANGE_COMPLETED: "교환 완료",
  EXCHANGE_REFUSAL: "교환 거절",
  EXCHANGE_ERROR: "교환 실패",
  CONFIRM_PURCHASE: "주문 승인",
  PICK_UP_IN_PROGRESS: "수거중",
  PICK_UP_COMPLETED: "수거 완료",
};

export enum OrderStatus {
  NEW = "NEW",
  PREPARING = "PREPARING",
  SHIPPING = "SHIPPING",
  SHIPPING_COMPLETED = "SHIPPING_COMPLETED",
  CONFIRM_PURCHASE = "CONFIRM_PURCHASE",
  CANCEL_REQUEST = "CANCEL_REQUEST",
  CANCEL_REFUSAL = "CANCEL_REFUSAL",
  CANCEL_COMPLETED = "CANCEL_COMPLETED",
  REFUND_REQUEST = "REFUND_REQUEST",
  REFUND_REFUSAL = "REFUND_REFUSAL",
  REFUND_COMPLETED = "REFUND_COMPLETED",
  REFUND_PICK_UP_ING = "REFUND_PICK_UP_ING",
  REFUND_PICK_UP_COMPLETED = "REFUND_PICK_UP_COMPLETED",
  EXCHANGE_REQUEST = "EXCHANGE_REQUEST",
  EXCHANGE_REFUSAL = "EXCHANGE_REFUSAL",
  EXCHANGE_COMPLETED = "EXCHANGE_COMPLETED",
  EXCHANGE_PICK_UP_ING = "EXCHANGE_PICK_UP_ING",
  EXCHANGE_PICK_UP_COMPLETED = "EXCHANGE_PICK_UP_COMPLETED",
  EXCHANGE_ING = "EXCHANGE_ING",
}

export const claimStatusType = {
  CONFIRM_PURCHASE: "구매 확인",
  CANCEL_REQUEST: "취소 요청",
  CANCEL_REFUSAL: "취소 거절",
  CANCEL_COMPLETED: "취소 완료",
  REFUND_REQUEST: "환불 요청",
  REFUND_REFUSAL: "환불 거절",
  REFUND_COMPLETED: "환불 완료",
  REFUND_PICK_UP_ING: "환불 수거 진행중",
  REFUND_PICK_UP_COMPLETED: "환불 수거 완료",
  EXCHANGE_REQUEST: "교환 요청",
  EXCHANGE_REFUSAL: "교환 거부",
  EXCHANGE_COMPLETED: "교환 완료",
  EXCHANGE_PICK_UP_ING: "교환 수거 진행중",
  EXCHANGE_PICK_UP_COMPLETED: "교환 수거 완료",
  EXCHANGE_ING: "교환중",
};

export enum ShipmentStatus {
  SHIPPING = "SHIPPING",
  REFUND_PICK_UP = "REFUND_PICK_UP",
  EXCHANGE_PICK_UP = "EXCHANGE_PICK_UP",
  EXCHANGE_PICK_UP_AGAIN = "EXCHANGE_PICK_UP_AGAIN",
}
